pool:
  name: Azure Pipelines

trigger: none

parameters:
- name: applyChanges
  displayName: Apply changes
  type: boolean
  default: false

resources:
  repositories:
    - repository: templates
      type: git
      name: "mateusclira-infra"
      ref: "refs/heads/master" 

stages:
  - stage: Build
    displayName: "Build"
    dependsOn: []
    variables:
      - group: dev
    jobs:
    - job: terraform
      displayName: "Terraform Job"
      steps:
        - template: ./templates/az-template.yaml
          parameters:
            serviceConnectionName: 'mateusclira sp'
            applyChanges: ${{ parameters.applyChanges }}
            terraformRgName: "rg-dev-mateusclira-sp"
            terraformWorkingFolder:  "./infra"
            terraformStorageAccountName : "mateuscliradevsp"
            stage: "Build"

    - job: Docker
      displayName: Build and Push Image
      dependsOn: terraform
      steps:
      - task: Docker@2
        displayName: Build and push an image to container registry
        inputs:
          command: buildAndPush
          repository: 'pythonapp'
          dockerfile: '$(Build.SourcesDirectory)/app/Dockerfile'
          containerRegistry: 'mateusclira docker'
          tags: |
            $(Build.BuildId)


  - stage: prd
    displayName: "Production"
    dependsOn: Build
    variables:
      - group: "prd"     
    jobs:
    - deployment: GetApprovals
      displayName: "Get Business Owner approval"
      environment: 'prd'
      strategy:
          runOnce:
            deploy:
                steps:
                - script: echo "Approved"
    - job: azureUpdate
      displayName: "Update Azure Resources"
      steps:
        - template: templates/az-template.yaml
          parameters:
            applyChanges: ${{ parameters.applyChanges }}
            serviceConnectionName: "mateusclira"
            terraformRgName: "rg-prd-mateusclira"
            terraformWorkingFolder:  "./infra"
            terraformStorageAccountName : "mateuscliraprd"     
            stage: "prd"